blog/urls.py
from django.urls import path
from . import views
from blog.apps import BlogConfig


app_name = 'blog'

urlpatterns = [
    path('create/', views.BlogCreateView.as_view(), name='create'),
    path('list/', views.BlogListView.as_view(), name='list'),
    path('view/<int:pk>', views.BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', views.BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', views.BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>', views.toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('contacts/', include('catalog.urls')),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls', namespace='users'))
]

blog/models.py
from django.db import models

# Create your models here.
NULLABLE = {'blank': True, 'null': True}


class BlogWriter(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='Slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое', **NULLABLE)
    image = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    date_of_creation = models.DateField(verbose_name='дата создания', auto_now_add=True)
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    view_count = models.IntegerField(default=0, verbose_name="Просмотры")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Запись блога"
        verbose_name_plural = "Записи блога"

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.models import BlogWriter


class BlogCreateView(CreateView):
    model = BlogWriter
    fields = ('title', 'content', 'image',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_note = form.save()
            new_note.slug = slugify(new_note.title)
            new_note.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = BlogWriter
    fields = ('title', 'content', 'image',)

    def form_valid(self, form):
        if form.is_valid():
            new_note = form.save()
            new_note.slug = slugify(new_note.title)
            new_note.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = BlogWriter

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = BlogWriter

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = BlogWriter
    success_url = reverse_lazy('blog:list')


def toggle_activity(request, pk):
    blog_item = get_object_or_404(BlogWriter, pk=pk)
    if blog_item.is_published:
        blog_item.is_published = False
    else:
        blog_item.is_published = True

    blog_item.save()

    return redirect(reverse('blog:list'))

blog/templates/blog/blogwriter_confirm_delete.html
{% extends "catalog/base.html" %}
{% block content %}

    <div class="col-6" style="text-align: center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Хотите удалить материал? {{ object.title }}</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <button type="submit" href="{% url 'blog:list' %}" class="btn btn-danger">
                        Подтвердить
                    </button>
                    <a type="button" href="{% url 'blog:list' %}" class="btn btn-success">
                        Отменить
                    </a>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blogwriter_detail.html
{% extends "catalog/base.html" %}
{% block content %}

    <div class="container">
            <div class="row text-center">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object|title }} ({{ object.slug }})</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-center m-3">
                            <img src="/media/{{ object.image }}"/>
                            <div class="d-flex justify-content-between align-items-center">
                                <h6 class="card-title pricing-card-title"> {{ object.content }}</h6>
                            </div>
                        </ul>
                    </div>
                    <div class="card-footer">
                        Просмотры {{ object.view_count }}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

blog/templates/blog/blogwriter_form.html
{% extends "catalog/base.html" %}
{% block content %}

    <div class="col-3" style="text-align: center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Создайте статью</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Опубликовать
                        {% endif %}
                    </button>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blogwriter_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Skyblog</h1>
        <p class="lead">Skyblog - отличный способ вести свои заметки и записи</p>
    </div>

    <div class="container">
        <div class="row text-center">
            <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'blog:create' %}">
                Добавить материал
            </a>
        </div>
    </div>
    {% for object in object_list %}
        <div class="container">
            <div class="row text-center">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object|title }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-center m-3">
                            <img src="/media/{{ object.image }}"/>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url 'blog:view' object.pk%}"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    <a href="{% url 'blog:edit' object.pk%}"
                                       class="btn btn-sm btn-outline-secondary">Edit</a>
                                    <a href="{% url 'blog:delete' object.pk%}"
                                       class="btn btn-sm btn-outline-danger">Delete</a>
                                </div>
                                {% if object.is_published %}
                                <a class="btn-outline-danger" href="{% url 'blog:toggle_activity' object.pk %}">
                                    Снять с публикации
                                </a>
                                {% else %}
                                <a class="btn-outline-danger" href="{% url 'blog:toggle_activity' object.pk %}">
                                    Опубликовать
                                </a>
                                {% endif %}
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}