blog/urls.py
from django.urls import path
from . import views
from blog.apps import BlogConfig


app_name = 'blog'

urlpatterns = [
    path('create/', views.BlogCreateView.as_view(), name='create'),
    path('list/', views.BlogListView.as_view(), name='list'),
    path('view/<int:pk>', views.BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', views.BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', views.BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>', views.toggle_activity, name='toggle_activity'),
]

catalog/urls.py
from django.urls import include, path

from . import views
from .views import ContactsView, CatalogItemsView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, ProductListView, AddVersionView

app_name = 'catalog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('catalog/', CatalogItemsView.as_view(), name='catalog_items'),
    path('product/<int:product_id>/',
         ProductDetailView.as_view(), name='product_detail'),
    path('product/', include([
        path('product/create/', ProductCreateView.as_view(),
             name='create_product'),

        path('update/<int:pk>/', ProductUpdateView.as_view(),
             name='product_update'),

        path('delete/<int:pk>/', ProductDeleteView.as_view(),
             name='product_delete'),

        path('product/list/', ProductListView.as_view(), name='product_list'),
        path('add_version/<int:product_id>/',
             views.AddVersionView.as_view(), name='add_version'),
    ])),
]

config/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('contacts/', include('catalog.urls')),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls', namespace='users'))
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verification_user, generate_new_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verification/<int:user_pk>/<str:verification_code>/',
         verification_user, name='verification'),
    # path('recovery_password/', PasswordResetView.as_view(template_name='users/password_reset.html'),
    #      name='recovery_password'),
    path('profile/generate_new_password/',
         generate_new_password, name='generate_new_password')
]

catalog/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth import get_user_model
from users.models import User
from django.contrib.auth.models import Permission
from django.db.models.signals import post_migrate

NULLABLE = {'blank': True, 'null': True}
User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    image = models.ImageField(upload_to='products/',
                              verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    purchase_price = models.FloatField(verbose_name='цена за покупку')
    date_of_creation = models.DateField(
        verbose_name='дата создания', auto_now_add=True)
    last_modified_date = models.DateField(
        verbose_name='дата последнего изменения', auto_now=True)
    versions = models.ManyToManyField(
        'Version', related_name='products', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='products', verbose_name='пользователь')
    is_published = models.BooleanField(
        default=False, verbose_name='опубликовано')

    def __str__(self):
        return f'{self.name} {self.description} {self.purchase_price} '

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        permissions = [
            (
                'set_is_published',
                'Can publish post'
            ),
            (
                'set_description',
                'Can change description'
            ),
            (
                'set_category',
                'Can change category'
            )
        ]


class Version(models.Model):
    product = models.ForeignKey(
        'Product', on_delete=models.CASCADE, verbose_name='id_product')
    number_version = models.IntegerField(verbose_name='номер_версии')
    name = models.CharField(max_length=100, verbose_name='наименование')
    current_version = models.BooleanField(
        verbose_name='признак_текущей_версии')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'


@receiver(post_migrate)
def create_permissions(sender, **kwargs):
    if sender.name == 'your_app_name':
        Permission.objects.create(
            codename='can_edit_product', name='Can Edit Product')
        Permission.objects.create(
            codename='can_publish_post', name='Can Publish Post')
        Permission.objects.create(
            codename='can_change_description', name='Can Change Description')
        Permission.objects.create(
            codename='can_change_category', name='Can Change Category')

catalog/forms.py
from django import forms
from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'category',
                  'image', 'purchase_price',)
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
        }

    version_name = forms.CharField(
        max_length=100, required=False, label='Имя версии')
    version_number = forms.IntegerField(required=False, label='Номер версии')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.instance.id:
            # Если объект еще не создан (редактирование), скрываем поля версии
            self.fields['version_name'].widget = forms.HiddenInput()
            self.fields['version_number'].widget = forms.HiddenInput()

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        prohibited_list = ['казино', 'криптовалюта', 'крипта',
                           'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for obj in prohibited_list:
            if obj in cleaned_data:
                raise forms.ValidationError("Продукт запрещен на площадке")

        return cleaned_data

    def save(self, commit=True):
        product = super().save(commit=False)

        version_name = self.cleaned_data.get('version_name')
        version_number = self.cleaned_data.get('version_number')

        if version_name and version_number:
            version = Version.objects.create(
                product=product,
                name=version_name,
                number_version=version_number,
                current_version=True,
            )
            product.versions.add(version)

        if commit:
            product.save()

        return product


class CreateProductForm(ProductForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['version_name'].widget = forms.HiddenInput()
        self.fields['version_number'].widget = forms.HiddenInput()


class EditProductForm(ProductForm):
    pass


class ModeratorProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        prohibited_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for obj in prohibited_list:
            if obj in cleaned_data:
                raise forms.ValidationError("Продукт запрещен на площадке")

        return cleaned_data


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ('name', 'number_version', 'current_version',)

catalog/views.py
from catalog.forms import EditProductForm, ModeratorProductForm, ProductForm, VersionForm
from catalog.models import Category, Product
from django.views import View
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponseForbidden, HttpResponseRedirect

from catalog.services import get_cached_categories
from .models import Category, Product, Version
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Group
from django.views.decorators.cache import cache_page


class IndexView(View):
    def get(self, request):
        products = Product.objects.all()

        for product in products:
            if len(product.description) > 100:
                product.description = product.description[:100] + '...'

        context = {
            'products': products,
        }
        return render(request, 'catalog/index.html', context)


class ContactsView(View):
    def post(self, request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name}, {phone}, {message}')
        return HttpResponseRedirect('/')

    def get(self, request):
        return render(request, 'catalog/contacts.html')


@method_decorator(login_required, name='dispatch')
class CatalogItemsView(View):
    def get(self, request):
        categories = get_cached_categories()
        products = Product.objects.all()
        context = {
            'categories': categories,
            'products': products,
        }
        return render(request, 'catalog/catalog_items.html', context)


@method_decorator(login_required, name='dispatch')
class ProductDetailView(View):
    template_name = 'catalog/product_detail.html'

    @cache_page(60 * 15)
    def get(self, request, product_id):
        product = get_object_or_404(Product, pk=product_id)
        versions = product.versions.all()

        return render(request, self.template_name, {'product': product, 'versions': versions})


@method_decorator(login_required, name='dispatch')
class ProductCreateView(View):
    def post(self, request):
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()

            version_name = form.cleaned_data.get('version_name')
            version_number = form.cleaned_data.get('version_number')

            if version_name and version_number:
                version = Version.objects.create(
                    product=product,
                    name=version_name,
                    number_version=version_number,
                    current_version=True
                )

            return redirect('catalog:product_list')

    def get(self, request):
        form = ProductForm()
        return render(request, 'catalog/product_form.html', {'form': form})


class ProductUpdateView(PermissionRequiredMixin, View):

    permission_required = 'catalog.can_edit_product'
    raise_exception = True

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        form = EditProductForm(request.POST, instance=product)

        if not request.user.has_perm('catalog.can_edit_product'):
            return HttpResponseForbidden("У вас нет прав для выполнения этого действия")

        if form.is_valid():
            form.save()
            return redirect('catalog:product_detail', product_id=product.pk)

    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        form = EditProductForm(instance=product)
        return render(request, 'catalog/product_form.html', {'form': form, 'product': product})


class ProductDeleteView(View):
    def post(self, request, pk):
        Product.objects.get(pk=pk).delete()
        return redirect('product:list')


class ProductListView(View):
    def get(self, request):
        products = Product.objects.all()
        return render(request, 'catalog/product_list.html', {'products': products})


@method_decorator(login_required, name='dispatch')
class AddVersionView(View):
    def post(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        version_form = VersionForm(request.POST)
        if version_form.is_valid():
            version = version_form.save(commit=False)
            version.product = product
            version.save()
            return redirect('product_detail', product_id=product.id)

    def get(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        version_form = VersionForm()
        return render(request, 'add_version.html', {'version_form': version_form, 'product': product})

catalog/templates/catalog/add_version.html
{% extends 'catalog/base.html' %}

{% block content %}
  <h2>Add Version for {{ product.name }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ version_form.as_p }}
    <button type="submit">Save Version</button>
  </form>
  <a href="{% url 'catalog:product_detail' product.id %}">Back to Product Detail</a>
{% endblock %}

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
            background-color: #f7f7f7;
        }
        .header {
            display: flex;
            flex-direction: row;
            align-items: center;
            justify-content: space-between;
            padding: 15px;
            background-color: #fff;
            border-bottom: 1px solid #ddd;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .header h5 {
            margin: 0;
            font-weight: normal;
        }
        nav a {
            margin-left: 15px;
            text-decoration: none;
            color: #333;
        }
        .pricing-header {
            padding: 50px 0;
            background-color: #f9f9f9;
        }
        .pricing-header h1 {
            margin-bottom: 20px;
        }
        .card {
            border: 1px solid #ddd;
            border-radius: 5px;
            overflow: hidden;
            margin-bottom: 20px;
        }
        .card-header {
            background-color: #007bff;
            color: #fff;
            padding: 15px;
        }
        .card-body {
            padding: 20px;
        }
        .card-title {
            font-size: 36px;
            margin-bottom: 20px;
        }
        .list-unstyled li {
            padding: 5px 0;
        }
        .footer {
            padding: 50px 0;
            background-color: #fff;
            border-top: 1px solid #ddd;
        }
        .footer ul {
            list-style: none;
            padding: 0;
        }
        .footer ul li {
            margin-bottom: 10px;
        }
        .text-muted {
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <h5 class="font-weight-normal">Skystore</h5>
        <nav>
            <a href="{% url 'catalog:catalog_items' %}" class="btn btn-outline-primary">Каталог</a>
            <a href="/contacts/" class="btn btn-outline-primary">Контакты</a>
            
            {% if user.is_authenticated %}
                <a href="{% url 'users:profile' %}" class="btn btn-outline-primary">Профиль</a>
                <a href="{% url 'users:logout' %}" class="btn btn-outline-primary">Выйти</a>
            {% else %}
                <a href="{% url 'users:login' %}" class="btn btn-outline-primary">Войти</a>
                <a href="{% url 'users:register' %}" class="btn btn-outline-primary">Зарегистрироваться</a>
            {% endif %}
        </nav>
    </div>
<div class="header">
    <h5 class="font-weight-normal">Skystore</h5>
    <nav>
        <a href="{% url 'catalog:catalog_items' %}" class="btn btn-outline-primary">Каталог</a>

        <a href="/contacts/" class="btn btn-outline-primary">Контакты</a>
    </nav>
</div>
<div class="pricing-header">
    <h1>Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card">
                <div class="card-header">
                    <h4 class="font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title">$ 140</h1>
                    <ul class="list-unstyled">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a href="#" class="text-muted">Рассылки</a></li>
                    <li><a href="#" class="text-muted">Телеграм боты</a></li>
                    <li><a href="#" class="text-muted">Полезные утилиты</a></li>
                    <li><a href="#" class="text-muted">Веб-приложения</a></li>
                    <li><a href="#" class="text-muted">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a href="#" class="text-muted">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a href="/contacts/" class="text-muted">Контакты</a></li>
                    <li><a href="/blog/list" class="text-muted">блог</a></li>
                    <li><a href="{% url 'catalog:create_product' %}" class="btn btn-outline-primary">Добавить продукт</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </footer>
</div>
{% block content %}
{% endblock %}
</body>
</html>

catalog/templates/catalog/catalog_items.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- Вывод категорий -->
<h2>Категории</h2>
<ul>
    {% for category in categories %}
    <li>{{ category.name }}</li>
    <!-- Здесь можете выводить другие данные о категориях -->
    {% endfor %}
</ul>

<!-- Вывод продуктов -->
<h2>Продукты</h2>
<ul>
    {% for product in products %}
    <li>{{ product.name }} - {{ product.description }} - {{ product.purchase_price }}</li>
    <!-- Здесь можете выводить другие данные о продуктах -->
    {% endfor %}
</ul>
</body>
</html>

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore - Контакты</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f8f9fa;
            color: #333;
            margin: 0;
            padding: 0;
        }

        .navbar {
            background-color: #fff;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .card {
            border: none;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .card-header {
            background-color: #007bff;
            color: #fff;
            border-radius: 10px 10px 0 0;
        }

        .form-control {
            border-radius: 5px;
        }

        .btn-outline-primary {
            color: #007bff;
            border-color: #007bff;
        }

        .btn-outline-primary:hover {
            color: #fff;
            background-color: #007bff;
            border-color: #007bff;
        }

        footer {
            background-color: #f8f9fa;
            padding: 50px 0;
            border-top: 1px solid #ddd;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-lg-9 col-md-6 col-sm-12 mx-auto mt-5">
            <div class="card mb-4">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond, WA, 98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 mx-auto mt-5">
            <div class="card mb-4">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="/contacts/">
                        <!-- замените "/submit_form" на свой URL или путь к скрипту обработки формы -->
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="О себе" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
</body>
</html>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row text-center">
    {% for product in products %}
    <div class="col-3">
        <div class="card">
            <div class="card-header">
                <h4 class="font-weight-normal">{{ product.name }}</h4>
            </div>
            <div class="card-body">
                <p>{{ product.description|truncatechars:100 }}</p>
                <p>Цена: ${{ product.purchase_price }}</p>
                <a href="{% url 'catalog:product_detail' product.id %}" class="btn btn-outline-primary">Подробнее</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
  <h2>Confirm Deletion</h2>
  <p>Are you sure you want to delete the product "{{ product.name }}"?</p>
  <form method="post" action="{% url 'product:delete' product.id %}">
    {% csrf_token %}
    <button type="submit">Yes, delete it</button>
    <form method="post" action="{% url 'catalog:product:delete' product.id %}">

  </form>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
  <h2>{{ product.name }} Details</h2>
  <p>Description: {{ product.description }}</p>
  <p>Category: {{ product.category.name }}</p>
  <p>Purchase Price: {{ product.purchase_price }}</p>

  <h3>Versions:</h3>
  <ul>
    {% for version in versions %}
      <li>{{ version.name }} (Version {{ version.number_version }})</li>
    {% endfor %}
  </ul>

  <a href="{% url 'catalog:product_update' product.id %}">Edit</a>
  <br>
  <a href="{% url 'catalog:product_list' %}">Back to Product List</a>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
  <h2>{% if product.id %}Edit Product{% else %}Create Product{% endif %}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% if product.id %}
      <label for="id_version_name">Версия продукта:</label>
      {{ form.version_name }}
      <label for="id_version_number">Номер версии:</label>
      {{ form.version_number }}
    {% endif %}
    <button type="submit">Save</button>
  </form>
  
  <a href="{% url 'catalog:product_list' %}">Back to Product List</a>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
  <h2>Product List</h2>
  <ul>
    {% for product in products %}
      <li>
        <a href="{% url 'catalog:product_detail' product.id %}">{{ product.name }}</a>
            <a href="{% url 'catalog:product_update' product.id %}">Edit</a>
            <a href="{% url 'catalog:product_delete' product.id %}">Delete</a>
      </li>
    {% endfor %}
  </ul>
  <a href="{% url 'catalog:create_product' %}">Create New Product</a>
{% endblock %}